# Generated by Django 4.0.1 on 2023-06-14 18:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=70)),
                ('model', models.CharField(max_length=70)),
                ('electro', models.BooleanField(default=False)),
                ('production_year', models.DateField()),
                ('mileage', models.FloatField(default=0)),
                ('range', models.FloatField()),
                ('color', models.IntegerField(choices=[(0, 'black'), (1, 'white'), (2, 'red'), (3, 'blue'), (4, 'yellow'), (5, 'gray'), (6, 'silver'), (7, 'green'), (8, 'brown'), (9, 'orange')], default=0)),
                ('image', models.ImageField(blank=True, upload_to='transport')),
                ('type', models.IntegerField(choices=[(0, 'sedan'), (1, 'hatchback'), (2, 'suv'), (3, 'crossover'), (4, 'coupe'), (5, 'convertible'), (6, 'minivan'), (7, 'pickup truck')], default=0)),
                ('description', models.CharField(max_length=500)),
                ('base_price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=100, null=True)),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('transport', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transport.transport')),
            ],
        ),
    ]
