# Generated by Django 4.0.1 on 2023-06-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
