# Generated by Django 4.0.1 on 2023-06-13 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0003_transport_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_location', models.IntegerField(choices=[(0, 'Ukraine, Lviv. Stepan Bandera Street, 12.'), (1, 'Ukraine, Rivne. Soborna Street, 12a.'), (2, 'Ukraine, Ternopil. Lystopadova Street, 5.'), (3, 'Ukraine, Ivano-Frankivsk. Mykhailo Hrushevsky Street, 21.')], default=0)),
                ('end_location', models.IntegerField(choices=[(0, 'Ukraine, Lviv. Stepan Bandera Street, 12.'), (1, 'Ukraine, Rivne. Soborna Street, 12a.'), (2, 'Ukraine, Ternopil. Lystopadova Street, 5.'), (3, 'Ukraine, Ivano-Frankivsk. Mykhailo Hrushevsky Street, 21.')], default=0)),
                ('bill', models.FloatField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('transport', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transport.transport')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
