# Generated by Django 4.0.1 on 2023-06-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_location', models.IntegerField(choices=[(0, 'Ukraine, Lviv. Stepan Bandera Street, 12.'), (1, 'Ukraine, Rivne. Soborna Street, 12a.'), (2, 'Ukraine, Ternopil. Lystopadova Street, 5.'), (3, 'Ukraine, Ivano-Frankivsk. Mykhailo Hrushevsky Street, 21.')], default=0)),
                ('end_location', models.IntegerField(choices=[(0, 'Ukraine, Lviv. Stepan Bandera Street, 12.'), (1, 'Ukraine, Rivne. Soborna Street, 12a.'), (2, 'Ukraine, Ternopil. Lystopadova Street, 5.'), (3, 'Ukraine, Ivano-Frankivsk. Mykhailo Hrushevsky Street, 21.')], default=0)),
                ('bill', models.FloatField(default=0)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
    ]
