# Generated by Django 4.0.1 on 2023-06-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('transport', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='transport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transport.transport'),
        ),
    ]
